//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SensoresAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sensores
    {
        public int idSensor { get; set; }
        public string latitude { get; set; }
        public string longitude { get; set; }
        public string cidade { get; set; }
        public string estado { get; set; }
        public string bairoo { get; set; }
        public string rua { get; set; }
        public string pais { get; set; }
        public string luminosidade { get; set; }
        public string temperatura { get; set; }
        public string umidade { get; set; }
        public string proximidade { get; set; }
        public Nullable<System.DateTime> dataEnvio { get; set; }
    }
}
